from __future__ import annotations

from typing import Any, Protocol

class BoundLogger(Protocol):
    def bind(self, **kwargs: Any) -> BoundLogger: ...
    def info(self, event: str, /, **kwargs: Any) -> None: ...
    def warning(self, event: str, /, **kwargs: Any) -> None: ...
    def error(self, event: str, /, **kwargs: Any) -> None: ...
    def exception(self, event: str, /, **kwargs: Any) -> None: ...
    def debug(self, event: str, /, **kwargs: Any) -> None: ...


def get_logger(*args: Any, **kwargs: Any) -> BoundLogger: ...
