from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Sequence

class Expr:
    def alias(self, name: str) -> Expr: ...
    def shift(self, periods: int) -> Expr: ...
    def fill_null(self, strategy: str | None = None, value: Any | None = None) -> Expr: ...
    def __mul__(self, other: Any) -> Expr: ...
    def __add__(self, other: Any) -> Expr: ...

class Series:
    def to_list(self) -> list[Any]: ...
    def __iter__(self) -> Iterable[Any]: ...
    def __getitem__(self, index: int) -> Any: ...
    def to_numpy(self) -> Any: ...

class DataFrame:
    height: int
    width: int

    @property
    def columns(self) -> list[str]: ...

    def write_parquet(self, file: str | Path) -> None: ...
    def sort(self, by: str | Sequence[str], *args: Any, **kwargs: Any) -> DataFrame: ...
    def __getitem__(self, key: str | slice | int) -> Series | DataFrame: ...
    def row(self, index: int, named: bool = False) -> Any: ...
    def __len__(self) -> int: ...
    def clone(self) -> DataFrame: ...

    # Convenience helpers used throughout the codebase
    def to_dicts(self) -> list[dict[str, Any]]: ...
    def with_columns(self, *exprs: Any, **named_exprs: Any) -> DataFrame: ...
    def select(self, *exprs: Any, **named_exprs: Any) -> DataFrame: ...
    def append(self, item: Any) -> None: ...


def concat(items: Sequence[DataFrame], how: str | None = None) -> DataFrame: ...
def col(name: str) -> Expr: ...
