"""Type definitions for monitoring system."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class AlertSeverity(Enum):
    """Alert severity levels."""
    CRITICAL = "CRITICAL"  # Immediate action required
    WARNING = "WARNING"    # Needs attention soon
    INFO = "INFO"          # Informational only


class HealthStatus(Enum):
    """Overall health status."""
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


@dataclass
class HealthMetric:
    """A single health metric measurement."""
    name: str
    value: float
    baseline: Optional[float]
    threshold: float
    is_healthy: bool
    timestamp: datetime
    context: Dict[str, Any]


@dataclass
class HealthAlert:
    """An alert generated by health monitoring."""
    severity: AlertSeverity
    title: str
    message: str
    metric: Optional[HealthMetric]
    suggested_actions: List[str]
    context: Dict[str, Any]
    timestamp: datetime
    alert_id: str


@dataclass
class PatternHealthReport:
    """Health report for a trading pattern."""
    pattern_id: int
    pattern_name: str
    current_win_rate: float
    baseline_win_rate: float
    recent_trades: int
    status: HealthStatus
    degradation_pct: float
    issues: List[str]
    timestamp: datetime


@dataclass
class ErrorSummary:
    """Summary of errors over a time period."""
    error_type: str
    count: int
    first_seen: datetime
    last_seen: datetime
    impact: str  # 'NONE', 'LOW', 'MEDIUM', 'HIGH'
    affected_trades: List[int]
    sample_messages: List[str]
